services:
  gradio-app:
    container_name: chatbot-rag
    restart: on-failure
    ports:
      - 7860:7860
    volumes:
      - ../models:/app/models
      - ../embed_models:/app/embed_models
      - ../config.py:/app/config.py
    env_file:
      - path: ../.env
        required: true
