services:
  app:
    extends:
      file: ../docker/compose.cpu.yml
      service: app
    build:
      context: ..
      dockerfile: cpu.Dockerfile
    image: local/chatbot-rag:main-cpu

  llamacpp:
    extends:
      file: ../docker/compose.cpu.yml
      service: llamacpp